apiVersion: "zalando.org/v1"
kind: PlatformCredentialsSet
metadata:
  name: {{{APPLICATION}}}-credentials-resource-wl
spec:
  application: metacontroller
  token_version: v2
  tokens:
    test-app:
      privileges: []